name: Tag and release

on:
  push:
    branches:
      - main
    paths:
      - 'lib/puppet/resource_api/version.rb'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
          tag_prefix: false
          # DEFAULT_BUMP: patch

          # TAG_CONTEXT: branch
          # WITH_V: false
          # Uncomment this if the tag and version file become out-of-sync and
          # you need to tag at a specific version.
          # CUSTOM_TAG:
      - name: Build gem
        uses: scarhand/actions-ruby@master
        with:
          args: build *.gemspec
      - name: Publish gem
        uses: scarhand/actions-ruby@master
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_JENKINS_GH_ACTIONS_PUSH }}
        with:
          args: push *.gem
